#!/usr/bin/env bash

echo "Resetting SMNRPX..."
rm -rf /etc/letsencrypt/accounts
rm -rf /etc/letsencrypt/archive
rm -rf /etc/letsencrypt/csr
rm -rf /etc/letsencrypt/keys
rm -rf /etc/letsencrypt/live/*
rm -rf /etc/letsencrypt/renewal
rm -rf /etc/letsencrypt/renewal-hooks
rm -rf /etc/letsencrypt/*.pem
echo "DONE, you can now relaunch the container..."